# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WisdomGrpcService.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='WisdomGrpcService.proto',
    package='com.javahelps.wisdom.service.gprc',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x17WisdomGrpcService.proto\x12!com.javahelps.wisdom.service.gprc\"\x15\n\x05\x45vent\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\xa3\x02\n\x06Wisdom\x12Z\n\x04send\x12(.com.javahelps.wisdom.service.gprc.Event\x1a(.com.javahelps.wisdom.service.gprc.Event\x12\\\n\x04\x66\x65\x65\x64\x12(.com.javahelps.wisdom.service.gprc.Event\x1a(.com.javahelps.wisdom.service.gprc.Event(\x01\x12_\n\x07receive\x12(.com.javahelps.wisdom.service.gprc.Event\x1a(.com.javahelps.wisdom.service.gprc.Event0\x01\x62\x06proto3')
)

_EVENT = _descriptor.Descriptor(
    name='Event',
    full_name='com.javahelps.wisdom.service.gprc.Event',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='data', full_name='com.javahelps.wisdom.service.gprc.Event.data', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=62,
    serialized_end=83,
)

DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
    DESCRIPTOR=_EVENT,
    __module__='WisdomGrpcService_pb2'
    # @@protoc_insertion_point(class_scope:com.javahelps.wisdom.service.gprc.Event)
))
_sym_db.RegisterMessage(Event)

_WISDOM = _descriptor.ServiceDescriptor(
    name='Wisdom',
    full_name='com.javahelps.wisdom.service.gprc.Wisdom',
    file=DESCRIPTOR,
    index=0,
    options=None,
    serialized_start=86,
    serialized_end=377,
    methods=[
        _descriptor.MethodDescriptor(
            name='send',
            full_name='com.javahelps.wisdom.service.gprc.Wisdom.send',
            index=0,
            containing_service=None,
            input_type=_EVENT,
            output_type=_EVENT,
            options=None,
        ),
        _descriptor.MethodDescriptor(
            name='feed',
            full_name='com.javahelps.wisdom.service.gprc.Wisdom.feed',
            index=1,
            containing_service=None,
            input_type=_EVENT,
            output_type=_EVENT,
            options=None,
        ),
        _descriptor.MethodDescriptor(
            name='receive',
            full_name='com.javahelps.wisdom.service.gprc.Wisdom.receive',
            index=2,
            containing_service=None,
            input_type=_EVENT,
            output_type=_EVENT,
            options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_WISDOM)

DESCRIPTOR.services_by_name['Wisdom'] = _WISDOM

# @@protoc_insertion_point(module_scope)
