---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(levelname)s - %(filename)s - %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

#    info_file_handler:
#        class: logging.handlers.RotatingFileHandler
#        level: INFO
#        formatter: simple
#        filename: info.log
#        maxBytes: 1024 # 1MB
#        backupCount: 20
#        encoding: utf8
#
#    error_file_handler:
#        class: logging.handlers.RotatingFileHandler
#        level: ERROR
#        formatter: simple
#        filename: errors.log
#        maxBytes: 1024 # 1MB
#        backupCount: 20
#        encoding: utf8

loggers:
    root:
        level: INFO
        handlers: [console]
        propagate: no

#root:
#    level: INFO
#    handlers: [console]
...
